### PR TITLE
Fix node  crashing

### PR DESCRIPTION
**Pull request by rustkas**
Add installing 'express'  module

### CODE REVIEW

**Comment by DanWahlin** [comment]
Appreciate the pull request. 

This example is using volumes to point the Docker container to the local copy of the source code so I don't want npm install to be run when the image is created. As long as npm install has been run locally as mentioned in the readme, Express will be installed there. Once docker-compose up is run that will start the container and the volume will point it to the local copy of source code (for development purposes). 

If you were building an image that included the source code as well as the required npm packages, then you would want npm install in the Dockerfile. That's not the goal with this repo though.

**Comment by rustkas** [comment]
Many thanks for the clarification. Maybe I'm not doing something. I tried to run the project, following your instructions. When I ran the project (docker-compose up) a message appeared in the log messages that the program could not find the express module. Therefore, I tried to install it additionally vie RUN directive. In the production of all OK. But in dev- is not. I worked on Linux.

**Comment by DanWahlin** [comment]
No problem. :-) Did you run `npm install` locally first? That would create the node_modules locally on your drive and then when docker-compose up is run it would link the container back to your local code.

As a heads-up, this is an older project that was created before the Angular CLI came out. If you want a more robust project that's for Angular 7 check out my other projects (here are a few):

https://github.com/DanWahlin/AngularCLI-NodeJS-MongoDB-CustomersService
https://github.com/DanWahlin/Angular-JumpStart (no docker in this one but a more robust sample app)

**Comment by rustkas** [comment]
I wrote `RUN npm install` first in configuraton file (*dockerfile).
On the next line I write `RUN  npm install express`

**Comment by rustkas** [comment]
I do not run `npn install` locally.

**Comment by rustkas** [comment]
Thank you very much for your explanatory comments and suggestions.

**Comment by DanWahlin** [comment]
Ok....if you go through all of the steps shown in the readme it should work for you.

**Comment by DanWahlin** [comment]
No problem.... appreciate you submitting a pull request. Most people don't take the time to contribute and try to help out so thanks again. 😀

**Comment by rustkas** [comment]
Dan. I have a question related to your README file content. Is it possible to use only docker's configuration files (without local installation of Node, MongoDB? I would like to do experiments only (I do not want to do a local installation of this software). Is it possible to launch a project without local installation? Like [so](https://www.digitalocean.com/community/tutorials/how-to-build-a-node-js-application-with-docker). 
Now I study docker tools.

**Comment by DanWahlin** [comment]
Yeah.... definitely. That's a bigger topic than I can cover here though. I have a course on Pluralsight.com called Docker for Web Developers that goes into all of that if you're interested. There are a lot of tutorials out there as well on the subject.

In a nutshell, you'd create a Dockerfile that builds an image that includes everything needed for the Node app. Then you'd run the container.

**Comment by rustkas** [comment]
I will definitely get acquainted with [your course](https://www.pluralsight.com/courses/docker-web-development) (I have it opened on one of the browser tabs already).

**Pull request closed without merging**
